apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 2
  strategy:
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: mtwatson/udacity-docker-final:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: helloworld
spec:
 type: LoadBalancer
 selector:
   app: helloworld
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: helloworld
