apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-docker-final
spec:
  selector:
    matchLabels:
      app: udacity-docker-final
  replicas: 2
  strategy:
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template: 
    metadata:
      labels:
        app: udacity-docker-final
    spec:
      containers:
      - name: udacity-docker-final
        image: mtwatson/udacity-docker-final:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: udacity-docker-final
spec:
 type: LoadBalancer
 selector:
   app: udacity-docker-final
 ports:
   - name: client
     protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 32080
 selector:
   app: udacity-docker-final
